name: Continuous Delivery
on:
  push:
    branches:
      - main

jobs:
  deliver:
    runs-on: ubuntu-latest   # Define o ambiente de execução (máquina virtual Ubuntu)

    steps:
          # Etapa 1: Faz o checkout do código do repositório
          - name: Check out repository code
            uses: actions/checkout@v4

          # Etapa 2: Simula o processo de Continuous Delivery
          - name: Simulando Continuous Delivery
            uses: actions/upload-artifact@v7
            with:
              name: projetozipado.zip
              path: |
                **/*.py
                README.md
